// MegaVault Product Catalog - Indian Rupee (INR / ₹)
// Category IDs: Audio ("1"), Wearables ("2"), Gaming ("3"), Electronics & Mobile Phones ("4"), Fashion ("5"), Smart Home ("6")

export const budgetCategoriesData = [
  { id: 'all', name: 'All Budgets', maxPrice: 100000, badge: 'Full Catalog' },
  { id: 'under-10k', name: 'Under ₹10,000', maxPrice: 10000, badge: 'Budget Vault' },
  { id: 'under-30k', name: 'Under ₹30,000', maxPrice: 30000, badge: 'Popular Range' },
  { id: 'under-50k', name: 'Under ₹50,000', maxPrice: 50000, badge: 'Pro Performance' },
  { id: 'under-1lakh', name: 'Under ₹1 Lakh', maxPrice: 100000, badge: 'Flagship Tech' }
];

export const categoriesData = [
  { id: '1', numericId: 1, name: 'Audio & Sound', itemCount: '7 Items', image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=600&q=80' },
  { id: '2', numericId: 2, name: 'Smart Wearables', itemCount: '6 Items', image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=600&q=80' },
  { id: '3', numericId: 3, name: 'Gaming & Gear', itemCount: '7 Items', image: 'https://images.unsplash.com/photo-1600080972464-8e5f35f63d08?auto=format&fit=crop&w=600&q=80' },
  { id: '4', numericId: 4, name: 'Electronics & Mobile Phones', itemCount: '12 Items', image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=600&q=80' },
  { id: '5', numericId: 5, name: 'Fashion & Wear', itemCount: '6 Items', image: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=600&q=80' },
  { id: '6', numericId: 6, name: 'Smart Home', itemCount: '7 Items', image: 'https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&w=600&q=80' }
];

export const allProductsData = [
  // ------------------- CATEGORY 1: AUDIO & SOUND (categoryId: "1") -------------------
  {
    id: '101',
    productCode: 'AUD-101',
    categoryId: '1',
    categorySlug: 'audio',
    categoryCode: 'AUD',
    title: 'Sony WH-CH720N Wireless Noise Cancelling Headphones (Black)',
    category: 'Audio',
    price: 4999,
    originalPrice: 6999,
    rating: 4.8,
    reviewsCount: 142,
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=600&q=80',
    description: 'Studio-grade spatial audio with active noise cancellation and 40-hour battery life.',
    isNew: true,
    badgeText: 'Bestseller'
  },
  {
    id: '102',
    productCode: 'AUD-102',
    categoryId: '1',
    categorySlug: 'audio',
    categoryCode: 'AUD',
    title: 'boAt Airdopes 141 Bluetooth TWS Earbuds (Bold Black, 42H Playtime)',
    category: 'Audio',
    price: 1999,
    originalPrice: 2999,
    rating: 4.5,
    reviewsCount: 210,
    image: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=600&q=80',
    description: 'Lightweight true wireless earbuds with quad mic ENC and IPX5 sweat protection.'
  },
  {
    id: '103',
    productCode: 'AUD-103',
    categoryId: '1',
    categorySlug: 'audio',
    categoryCode: 'AUD',
    title: 'JBL Charge 5 Portable Bluetooth Speaker (Squad Camo, IP67 Waterproof)',
    category: 'Audio',
    price: 7999,
    originalPrice: 10999,
    rating: 4.7,
    reviewsCount: 95,
    image: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=600&q=80',
    description: '60W RMS portable bluetooth party speaker with RGB lights and IPX7 body.'
  },
  {
    id: '104',
    productCode: 'AUD-104',
    categoryId: '1',
    categorySlug: 'audio',
    categoryCode: 'AUD',
    title: 'Samsung HW-B650 3.1ch Soundbar with Wireless Subwoofer (Dolby Audio)',
    category: 'Audio',
    price: 9999,
    originalPrice: 14999,
    rating: 4.8,
    reviewsCount: 78,
    image: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=600&q=80',
    description: '120W Dolby Digital soundbar with wireless subwoofer and HDMI ARC.'
  },
  {
    id: '105',
    productCode: 'AUD-105',
    categoryId: '1',
    categorySlug: 'audio',
    categoryCode: 'AUD',
    title: 'Audio-Technica AT2020 Cardioid Condenser Microphone (XLR)',
    category: 'Audio',
    price: 3999,
    originalPrice: 5999,
    rating: 4.6,
    reviewsCount: 64,
    image: 'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?auto=format&fit=crop&w=600&q=80',
    description: 'Professional XLR studio condenser microphone for podcasting and vocal recording.'
  },
  {
    id: '106',
    productCode: 'AUD-106',
    categoryId: '1',
    categorySlug: 'audio',
    categoryCode: 'AUD',
    title: 'Sennheiser HD 660S2 Open-Back Audiophile Headphones',
    category: 'Audio',
    price: 24999,
    originalPrice: 29999,
    rating: 4.9,
    reviewsCount: 38,
    image: 'https://images.unsplash.com/photo-1583394838336-acd977736f90?auto=format&fit=crop&w=600&q=80',
    description: 'Open-back planar magnetic audiophile reference headphones with lossless soundstage.'
  },
  {
    id: '107',
    productCode: 'AUD-107',
    categoryId: '1',
    categorySlug: 'audio',
    categoryCode: 'AUD',
    title: 'JBL Clip 4 Ultra-Portable Waterproof Bluetooth Speaker (Red)',
    category: 'Audio',
    price: 2499,
    originalPrice: 3499,
    rating: 4.6,
    reviewsCount: 165,
    image: 'https://images.unsplash.com/photo-1543512214-318c7553f230?auto=format&fit=crop&w=600&q=80',
    description: 'Rugged carabiner clip bluetooth speaker with punchy bass and 12h playtime.'
  },

  // ------------------- CATEGORY 2: SMART WEARABLES (categoryId: "2") -------------------
  {
    id: '201',
    productCode: 'WRB-201',
    categoryId: '2',
    categorySlug: 'wearables',
    categoryCode: 'WRB',
    title: 'Samsung Galaxy Watch6 Bluetooth (44mm, Graphite) | Body Composition',
    category: 'Wearables',
    price: 14999,
    originalPrice: 18999,
    rating: 4.9,
    reviewsCount: 98,
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=600&q=80',
    isNew: true,
    badgeText: 'Top Pick'
  },
  {
    id: '202',
    productCode: 'WRB-202',
    categoryId: '2',
    categorySlug: 'wearables',
    categoryCode: 'WRB',
    title: 'Noise ColorFit Pulse 2 Max 1.85" Display Smart Watch (Deep Wine)',
    category: 'Wearables',
    price: 2499,
    originalPrice: 3499,
    rating: 4.4,
    reviewsCount: 310,
    image: 'https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?auto=format&fit=crop&w=600&q=80',
    description: 'Ultra-light fitness band with 120+ sports modes, SpO2 monitoring, and 14-day battery.'
  },
  {
    id: '203',
    productCode: 'WRB-203',
    categoryId: '2',
    categorySlug: 'wearables',
    categoryCode: 'WRB',
    title: 'Garmin Instinct 2X Solar Titanium Rugged Outdoor GPS Watch',
    category: 'Wearables',
    price: 19999,
    originalPrice: 24999,
    rating: 4.9,
    reviewsCount: 42,
    image: 'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?auto=format&fit=crop&w=600&q=80',
    description: 'Military-grade titanium rugged smartwatch with dual-band GPS.'
  },
  {
    id: '204',
    productCode: 'WRB-204',
    categoryId: '2',
    categorySlug: 'wearables',
    categoryCode: 'WRB',
    title: 'Oura Ring Gen 3 Horizon Smart Health Ring (Heritage Black)',
    category: 'Wearables',
    price: 8999,
    originalPrice: 11999,
    rating: 4.7,
    reviewsCount: 53,
    image: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=600&q=80',
    description: 'Sleek smart ring tracking sleep stages, HRV, body temperature, and daily recovery.'
  },
  {
    id: '205',
    productCode: 'WRB-205',
    categoryId: '2',
    categorySlug: 'wearables',
    categoryCode: 'WRB',
    title: 'boAt Wave Call 1.69" HD Display Smartwatch with BT Calling',
    category: 'Wearables',
    price: 3499,
    originalPrice: 4999,
    rating: 4.5,
    reviewsCount: 180,
    image: 'https://images.unsplash.com/photo-1544117519-31a4b719223d?auto=format&fit=crop&w=600&q=80',
    description: 'HD touchscreen smartwatch with Bluetooth calling, dial pad, and 100+ cloud faces.'
  },
  {
    id: '206',
    productCode: 'WRB-206',
    categoryId: '2',
    categorySlug: 'wearables',
    categoryCode: 'WRB',
    title: 'Apple Watch Series 9 GPS (45mm, Midnight Aluminium Case)',
    category: 'Wearables',
    price: 38999,
    originalPrice: 44999,
    rating: 4.9,
    reviewsCount: 31,
    image: 'https://images.unsplash.com/photo-1510017803434-a899398421b3?auto=format&fit=crop&w=600&q=80',
    isNew: true,
    badgeText: 'Under 50k',
    description: 'Sapphire glass solar charging expedition watch with multi-continent topographic maps.'
  },

  // ------------------- CATEGORY 3: GAMING & GEAR (categoryId: "3") -------------------
  {
    id: '301',
    productCode: 'GAM-301',
    categoryId: '3',
    categorySlug: 'gaming',
    categoryCode: 'GAM',
    title: 'Keychron K2 V2 Wireless Mechanical Keyboard (Gateron G Pro Red)',
    category: 'Gaming',
    price: 3499,
    originalPrice: 4499,
    rating: 4.7,
    reviewsCount: 64,
    image: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=600&q=80',
    description: 'Hot-swappable mechanical switches with per-key RGB backlighting.'
  },
  {
    id: '302',
    productCode: 'GAM-302',
    categoryId: '3',
    categorySlug: 'gaming',
    categoryCode: 'GAM',
    title: 'Logitech G PRO X SUPERLIGHT Wireless Gaming Mouse (White)',
    category: 'Gaming',
    price: 1899,
    originalPrice: 2499,
    rating: 4.9,
    reviewsCount: 310,
    image: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&w=600&q=80',
    description: 'Ultralight 58g ergonomic gaming mouse with 26K DPI optical sensor.'
  },
  {
    id: '303',
    productCode: 'GAM-303',
    categoryId: '3',
    categorySlug: 'gaming',
    categoryCode: 'GAM',
    title: 'SteelSeries Arctis Nova 7 Wireless Multi-System Gaming Headset',
    category: 'Gaming',
    price: 2999,
    originalPrice: 3999,
    rating: 4.6,
    reviewsCount: 88,
    image: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=600&q=80',
    description: '7.1 virtual surround sound gaming headset with noise-canceling detachable mic.'
  },
  {
    id: '304',
    productCode: 'GAM-304',
    categoryId: '3',
    categorySlug: 'gaming',
    categoryCode: 'GAM',
    title: 'Flydigi Vader 3 Pro Wireless Hall Effect Gaming Controller',
    category: 'Gaming',
    price: 2799,
    originalPrice: 3799,
    rating: 4.7,
    reviewsCount: 112,
    image: 'https://images.unsplash.com/photo-1600080972464-8e5f35f63d08?auto=format&fit=crop&w=600&q=80',
    description: 'Hall effect anti-drift joysticks with customizable rear paddles.'
  },
  {
    id: '305',
    productCode: 'GAM-305',
    categoryId: '3',
    categorySlug: 'gaming',
    categoryCode: 'GAM',
    title: 'LG UltraGear 34" Curved WQHD 160Hz 1ms Gaming Monitor (34GP63A-B)',
    category: 'Gaming',
    price: 34999,
    originalPrice: 42999,
    rating: 4.9,
    reviewsCount: 36,
    image: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=600&q=80',
    isNew: true,
    description: 'Immersive 1500R curved 34-inch WQHD gaming monitor with 165Hz refresh rate.'
  },
  {
    id: '306',
    productCode: 'GAM-306',
    categoryId: '3',
    categorySlug: 'gaming',
    categoryCode: 'GAM',
    title: 'Secretlab TITAN Evo Ergonomic Gaming Chair (Stealth Leatherette)',
    category: 'Gaming',
    price: 14999,
    originalPrice: 19999,
    rating: 4.8,
    reviewsCount: 75,
    image: 'https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?auto=format&fit=crop&w=600&q=80',
    description: 'High-back lumbar support breathable mesh gaming chair with 4D armrests.'
  },
  {
    id: '307',
    productCode: 'GAM-307',
    categoryId: '3',
    categorySlug: 'gaming',
    categoryCode: 'GAM',
    title: 'Samsung 990 PRO NVMe PCIe 4.0 SSD 2TB (Up to 7450 MB/s)',
    category: 'Gaming',
    price: 11499,
    originalPrice: 15999,
    rating: 4.9,
    reviewsCount: 140,
    image: 'https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?auto=format&fit=crop&w=600&q=80',
    description: '7450MB/s ultra-fast Gen4 PCIe M.2 SSD for PS5 and high-end gaming rigs.'
  },

  // ------------------- CATEGORY 4: ELECTRONICS & MOBILE PHONES (categoryId: "4") -------------------
  {
    id: '401',
    productCode: 'ELE-401',
    categoryId: '4',
    categorySlug: 'electronics',
    categoryCode: 'ELE',
    title: 'Dell UltraSharp 27" 4K USB-C Hub Monitor (U2723QE) | IPS Black',
    category: 'Electronics',
    price: 28999,
    originalPrice: 34999,
    rating: 4.6,
    reviewsCount: 52,
    image: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=600&q=80',
    description: 'Ultra-crisp 4K IPS display with 99% DCI-P3 color gamut and USB-C 65W PD.'
  },
  {
    id: '402',
    productCode: 'ELE-402',
    categoryId: '4',
    categorySlug: 'electronics',
    categoryCode: 'ELE',
    title: 'Apple MacBook Pro Laptop M3 (14.2-inch, 8-core CPU, 18GB Unified Memory)',
    category: 'Electronics',
    price: 89999,
    originalPrice: 99999,
    rating: 4.9,
    reviewsCount: 45,
    image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=600&q=80',
    isNew: true,
    badgeText: 'Top Spec',
    description: 'Ultra-fast developer laptop featuring M3 chip, Liquid Retina display, and 18h battery.'
  },
  {
    id: '403',
    productCode: 'ELE-403',
    categoryId: '4',
    categorySlug: 'electronics',
    categoryCode: 'ELE',
    title: 'Apple iPad Air 5th Gen (10.9-inch, Wi-Fi, 64GB) - Space Grey',
    category: 'Electronics',
    price: 24999,
    originalPrice: 29999,
    rating: 4.7,
    reviewsCount: 89,
    image: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&w=600&q=80',
    description: 'Ultra-thin 120Hz AMOLED tablet with stylus support and quad speakers.'
  },
  {
    id: '404',
    productCode: 'ELE-404',
    categoryId: '4',
    categorySlug: 'electronics',
    categoryCode: 'ELE',
    title: 'Anker 737 Power Bank (PowerCore 24K, 140W 24,000mAh 3-Port)',
    category: 'Electronics',
    price: 2999,
    originalPrice: 4499,
    rating: 4.8,
    reviewsCount: 230,
    image: 'https://images.unsplash.com/photo-1609592424109-dd9892f1b177?auto=format&fit=crop&w=600&q=80',
    description: 'Heavy duty 65W Power Delivery power bank capable of charging laptops and phones.'
  },
  {
    id: '405',
    productCode: 'ELE-405',
    categoryId: '4',
    categorySlug: 'electronics',
    categoryCode: 'ELE',
    title: 'Anker Nebula Capsule 3 Laser 1080p Smart Mini Projector (Google TV)',
    category: 'Electronics',
    price: 11999,
    originalPrice: 16999,
    rating: 4.5,
    reviewsCount: 67,
    image: 'https://images.unsplash.com/photo-1535016120720-40c646be5580?auto=format&fit=crop&w=600&q=80',
    description: 'Compact 500 ANSI lumens portable projector with built-in Android OS.'
  },
  {
    id: '406',
    productCode: 'ELE-406',
    categoryId: '4',
    categorySlug: 'electronics',
    categoryCode: 'ELE',
    title: 'Sony BRAVIA 55" 4K Ultra HD Smart OLED Google TV (XR-55A80L)',
    category: 'Electronics',
    price: 48999,
    originalPrice: 62999,
    rating: 4.9,
    reviewsCount: 92,
    image: 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?auto=format&fit=crop&w=600&q=80',
    isNew: true,
    badgeText: 'Under 50k',
    description: '120Hz Dolby Vision OLED cinema smart TV with HDMI 2.1 gaming passthrough.'
  },
  {
    id: '407',
    productCode: 'ELE-407',
    categoryId: '4',
    categorySlug: 'electronics',
    categoryCode: 'ELE',
    title: 'ASUS Zenbook 14 OLED Laptop (Intel Core i7 13th Gen, 16GB RAM, 1TB SSD)',
    category: 'Electronics',
    price: 64999,
    originalPrice: 74999,
    rating: 4.8,
    reviewsCount: 56,
    image: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=600&q=80',
    description: 'Core i7 13th Gen laptop with 16GB DDR5 RAM, 1TB SSD, and 2.8K OLED screen.'
  },

  // 📱 AMAZON INDIA STYLE REALISTIC MOBILE PHONES:
  {
    id: '408',
    productCode: 'MOB-408',
    categoryId: '4',
    categorySlug: 'electronics',
    categoryCode: 'MOB',
    title: 'Redmi 13C 5G (Starlight Black, 4GB RAM, 128GB Storage) | MediaTek Dimensity 6100+',
    category: 'Electronics',
    price: 9999,
    originalPrice: 13999,
    rating: 4.6,
    reviewsCount: 310,
    image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=600&q=80',
    isNew: true,
    badgeText: 'Under 10k',
    description: 'Smooth 90Hz FHD+ display 5G smartphone with 50MP AI camera and 5000mAh battery.'
  },
  {
    id: '409',
    productCode: 'MOB-409',
    categoryId: '4',
    categorySlug: 'electronics',
    categoryCode: 'MOB',
    title: 'OnePlus 12R (Cool Blue, 8GB RAM, 128GB Storage) | Snapdragon 8 Gen 2 | 120Hz LTPO',
    category: 'Electronics',
    price: 27999,
    originalPrice: 32999,
    rating: 4.9,
    reviewsCount: 185,
    image: 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=600&q=80',
    isNew: true,
    badgeText: 'Under 30k',
    description: 'Snapdragon 8 Gen 2 processor, 120Hz curved AMOLED display, 67W fast charging.'
  },
  {
    id: '410',
    productCode: 'MOB-410',
    categoryId: '4',
    categorySlug: 'electronics',
    categoryCode: 'MOB',
    title: 'Vivo X100 5G (Asteroid Black, 12GB RAM, 256GB Storage) | Zeiss 1-inch Camera',
    category: 'Electronics',
    price: 46999,
    originalPrice: 54999,
    rating: 4.9,
    reviewsCount: 94,
    image: 'https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?auto=format&fit=crop&w=600&q=80',
    isNew: true,
    badgeText: 'Under 50k',
    description: '1-inch Sony IMX camera sensor with optics, 4K 60fps video, and IP68 rating.'
  },
  {
    id: '411',
    productCode: 'MOB-411',
    categoryId: '4',
    categorySlug: 'electronics',
    categoryCode: 'MOB',
    title: 'Samsung Galaxy Z Fold5 5G (Phantom Black, 12GB RAM, 512GB Storage) | S-Pen',
    category: 'Electronics',
    price: 84999,
    originalPrice: 99999,
    rating: 4.9,
    reviewsCount: 42,
    image: 'https://images.unsplash.com/photo-1565849904461-04a58ad377e0?auto=format&fit=crop&w=600&q=80',
    isNew: true,
    badgeText: 'Flagship Fold',
    description: 'Revolutionary dual AMOLED folding display phone with S-Pen support and titanium hinge.'
  },
  {
    id: '412',
    productCode: 'MOB-412',
    categoryId: '4',
    categorySlug: 'electronics',
    categoryCode: 'MOB',
    title: 'iQOO 12 5G (Legend White, 16GB RAM, 512GB Storage) | Snapdragon 8 Gen 3',
    category: 'Electronics',
    price: 39999,
    originalPrice: 47999,
    rating: 4.8,
    reviewsCount: 76,
    image: 'https://images.unsplash.com/photo-1546054454-aa26e2b734c7?auto=format&fit=crop&w=600&q=80',
    badgeText: 'Under 50k',
    description: '165Hz AMOLED gaming phone with ultrasonic shoulder triggers and vapor cooling fan.'
  },

  // ------------------- CATEGORY 5: FASHION & WEAR (categoryId: "5") -------------------
  {
    id: '501',
    productCode: 'FSH-501',
    categoryId: '5',
    categorySlug: 'fashion',
    categoryCode: 'FSH',
    title: 'Wildcraft 30L Waterproof Laptop Backpack with Anti-Theft Pockets',
    category: 'Fashion',
    price: 1799,
    originalPrice: 2499,
    rating: 4.8,
    reviewsCount: 175,
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=600&q=80',
    description: 'Weather-resistant laptop backpack with hidden anti-theft pockets and USB port.'
  },
  {
    id: '502',
    productCode: 'FSH-502',
    categoryId: '5',
    categorySlug: 'fashion',
    categoryCode: 'FSH',
    title: 'Ray-Ban Polarized Aviator Classic Sunglasses (Gold/G-15 Green Lens)',
    category: 'Fashion',
    price: 1299,
    originalPrice: 1999,
    rating: 4.6,
    reviewsCount: 120,
    image: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=600&q=80',
    description: 'Polarized aviator sunglasses with anti-glare TAC lenses and titanium frame.'
  },
  {
    id: '503',
    productCode: 'FSH-503',
    categoryId: '5',
    categorySlug: 'fashion',
    categoryCode: 'FSH',
    title: 'Tommy Hilfiger Men Leather Passcase Bifold Wallet with RFID',
    category: 'Fashion',
    price: 999,
    originalPrice: 1499,
    rating: 4.7,
    reviewsCount: 205,
    image: 'https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&w=600&q=80',
    description: 'Handcrafted top-grain leather bi-fold wallet with RFID blocking technology.'
  },
  {
    id: '504',
    productCode: 'FSH-504',
    categoryId: '5',
    categorySlug: 'fashion',
    categoryCode: 'FSH',
    title: 'Nike Air Zoom Pegasus 40 Men Running Shoes (White/Pure Platinum)',
    category: 'Fashion',
    price: 2499,
    originalPrice: 3999,
    rating: 4.6,
    reviewsCount: 140,
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=600&q=80',
    description: 'Ultra-cushioned responsive running shoes with breathable knit mesh upper.'
  },
  {
    id: '505',
    productCode: 'FSH-505',
    categoryId: '5',
    categorySlug: 'fashion',
    categoryCode: 'FSH',
    title: 'Columbia Omni-Heat Thermal USB Electric Heated Winter Jacket',
    category: 'Fashion',
    price: 4999,
    originalPrice: 6999,
    rating: 4.8,
    reviewsCount: 52,
    image: 'https://images.unsplash.com/photo-1548883354-7622d03aca27?auto=format&fit=crop&w=600&q=80',
    description: 'USB-powered heated jacket with 3 temperature control zones and windproof shell.'
  },
  {
    id: '506',
    productCode: 'FSH-506',
    categoryId: '5',
    categorySlug: 'fashion',
    categoryCode: 'FSH',
    title: 'Fossil Defender Leather Weekender Duffel Bag (Cognac Brown)',
    category: 'Fashion',
    price: 8499,
    originalPrice: 11999,
    rating: 4.9,
    reviewsCount: 68,
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=600&q=80',
    description: 'Handcrafted full-grain vintage leather weekender duffel bag with shoe compartment.'
  },

  // ------------------- CATEGORY 6: SMART HOME (categoryId: "6") -------------------
  {
    id: '601',
    productCode: 'SMH-601',
    categoryId: '6',
    categorySlug: 'smart-home',
    categoryCode: 'SMH',
    title: 'Philips Hue Play Smart RGB LED Light Bar (Base Kit, Alexa/Google)',
    category: 'Smart Home',
    price: 1499,
    originalPrice: 1999,
    rating: 4.6,
    reviewsCount: 89,
    image: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=600&q=80',
    description: 'App-controlled dynamic light bar with music rhythm sync and Alexa / Google support.'
  },
  {
    id: '602',
    productCode: 'SMH-602',
    categoryId: '6',
    categorySlug: 'smart-home',
    categoryCode: 'SMH',
    title: 'Xiaomi Smart Air Purifier 4 Pro with True HEPA Filter (OLED Touch Screen)',
    category: 'Smart Home',
    price: 6999,
    originalPrice: 9999,
    rating: 4.8,
    reviewsCount: 160,
    image: 'https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&w=600&q=80',
    description: 'True HEPA H13 filtration removing 99.97% of airborne allergens.'
  },
  {
    id: '603',
    productCode: 'SMH-603',
    categoryId: '6',
    categorySlug: 'smart-home',
    categoryCode: 'SMH',
    title: 'Roborock S8 LiDAR Robot Vacuum and Mop Cleaner (6000Pa Suction)',
    category: 'Smart Home',
    price: 21999,
    originalPrice: 28999,
    rating: 4.9,
    reviewsCount: 84,
    image: 'https://images.unsplash.com/photo-1518640467707-6811f4a6ab73?auto=format&fit=crop&w=600&q=80',
    isNew: true,
    description: 'LiDAR navigation robot vacuum with 4000Pa suction power and automatic mopping.'
  },
  {
    id: '604',
    productCode: 'SMH-604',
    categoryId: '6',
    categorySlug: 'smart-home',
    categoryCode: 'SMH',
    title: 'Yale Assure Lock 2 Keyless Fingerprint & PIN Smart Door Lock',
    category: 'Smart Home',
    price: 8999,
    originalPrice: 12999,
    rating: 4.7,
    reviewsCount: 96,
    image: 'https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&w=600&q=80',
    description: '5-in-1 keyless entry door lock with fingerprint scanner, PIN passcode, and app.'
  },
  {
    id: '605',
    productCode: 'SMH-605',
    categoryId: '6',
    categorySlug: 'smart-home',
    categoryCode: 'SMH',
    title: 'TP-Link Tapo P110 16A Smart Wi-Fi Plug with Energy Monitoring',
    category: 'Smart Home',
    price: 999,
    originalPrice: 1499,
    rating: 4.6,
    reviewsCount: 310,
    image: 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=600&q=80',
    description: '16A smart plug for heavy appliances with timer scheduling and energy tracking.'
  },
  {
    id: '606',
    productCode: 'SMH-606',
    categoryId: '6',
    categorySlug: 'smart-home',
    categoryCode: 'SMH',
    title: 'EZVIZ C6N 2K 360-Degree Smart Home Security Wi-Fi Camera',
    category: 'Smart Home',
    price: 3299,
    originalPrice: 4499,
    rating: 4.8,
    reviewsCount: 142,
    image: 'https://images.unsplash.com/photo-1557324232-b8917d3c3dcb?auto=format&fit=crop&w=600&q=80',
    description: '2K 360-degree pan-tilt AI motion tracking security camera with night vision & two-way talk.'
  },
  {
    id: '607',
    productCode: 'SMH-607',
    categoryId: '6',
    categorySlug: 'smart-home',
    categoryCode: 'SMH',
    title: 'HOBOT 298 Ultrasonic Automatic Glass & Window Cleaning Robot',
    category: 'Smart Home',
    price: 42999,
    originalPrice: 49999,
    rating: 4.9,
    reviewsCount: 29,
    image: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=600&q=80',
    isNew: true,
    badgeText: 'Under 50k',
    description: 'Dual-ultrasonic spray robotic glass and window cleaner with UPS backup safety power.'
  }
];

export const featuredProductsData = allProductsData.slice(0, 4);
export const trendingProductsData = allProductsData.slice(4, 12);
export const aiRecommendationsData = allProductsData.slice(0, 3).map((item, idx) => ({
  ...item,
  matchScore: 99 - idx * 2,
  aiReason: `High spec match & top rated item in India`
}));
